// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, omit_local_variable_types, omit_obvious_local_variable_types

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// 主题模式枚举
enum ThemeModeEnum {
  light,
  dark,
  system,
}

/// WiFi 测速结果
class WifiSpeedResult {
  WifiSpeedResult({
    required this.speed,
    required this.isSuccess,
    this.errorMessage,
  });

  /// WiFi 速度 (Mbps), -1 表示失败
  double speed;

  /// 是否成功
  bool isSuccess;

  /// 错误信息
  String? errorMessage;

  List<Object?> _toList() {
    return <Object?>[
      speed,
      isSuccess,
      errorMessage,
    ];
  }

  Object encode() {
    return _toList();  }

  static WifiSpeedResult decode(Object result) {
    result as List<Object?>;
    return WifiSpeedResult(
      speed: result[0]! as double,
      isSuccess: result[1]! as bool,
      errorMessage: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WifiSpeedResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(speed, other.speed) && _deepEquals(isSuccess, other.isSuccess) && _deepEquals(errorMessage, other.errorMessage);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// 当前连接 WiFi 的链路信息（频段 / 信道 / 信号强度）
/// 仅承载原生采集的原始值，展示格式（如 "5GHz (Ch 6, -42 dBm)"）由 Flutter 端拼接
class WifiConnectionInfo {
  WifiConnectionInfo({
    this.band,
    this.channel,
    this.rssi,
  });

  /// 频段 (2.4G, 5G, 6G)，来自 WifiUtils.checkCurrentWifiBand()，获取失败为 null
  String? band;

  /// 信道，来自 WifiUtils.getChannelByFrequency(frequency)，获取失败为 null
  int? channel;

  /// 信号强度 (dBm)，来自 wifiInfo.getRssi()，获取失败为 null
  int? rssi;

  List<Object?> _toList() {
    return <Object?>[
      band,
      channel,
      rssi,
    ];
  }

  Object encode() {
    return _toList();  }

  static WifiConnectionInfo decode(Object result) {
    result as List<Object?>;
    return WifiConnectionInfo(
      band: result[0] as String?,
      channel: result[1] as int?,
      rssi: result[2] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WifiConnectionInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(band, other.band) && _deepEquals(channel, other.channel) && _deepEquals(rssi, other.rssi);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// 应用运行时配置（启动时从原生一次性获取）
class AppRuntimeConfig {
  AppRuntimeConfig({
    required this.themeMode,
    required this.deviceId,
    required this.accessToken,
    this.connectedDeviceName,
    required this.language,
    required this.enableLog,
  });

  /// 主题模式
  ThemeModeEnum themeMode;

  /// 设备ID
  String deviceId;

  /// 访问令牌
  String accessToken;

  /// 当前连接设备的名称，未连接时为 null
  String? connectedDeviceName;

  /// 应用语言代码（如 en、fr），不依赖系统语言
  String language;

  /// 是否启用日志打印，Debug 模式为 true，Release 模式为 false
  bool enableLog;

  List<Object?> _toList() {
    return <Object?>[
      themeMode,
      deviceId,
      accessToken,
      connectedDeviceName,
      language,
      enableLog,
    ];
  }

  Object encode() {
    return _toList();  }

  static AppRuntimeConfig decode(Object result) {
    result as List<Object?>;
    return AppRuntimeConfig(
      themeMode: result[0]! as ThemeModeEnum,
      deviceId: result[1]! as String,
      accessToken: result[2]! as String,
      connectedDeviceName: result[3] as String?,
      language: result[4]! as String,
      enableLog: result[5]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AppRuntimeConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(themeMode, other.themeMode) && _deepEquals(deviceId, other.deviceId) && _deepEquals(accessToken, other.accessToken) && _deepEquals(connectedDeviceName, other.connectedDeviceName) && _deepEquals(language, other.language) && _deepEquals(enableLog, other.enableLog);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is ThemeModeEnum) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is WifiSpeedResult) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is WifiConnectionInfo) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is AppRuntimeConfig) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : ThemeModeEnum.values[value];
      case 130:
        return WifiSpeedResult.decode(readValue(buffer)!);
      case 131:
        return WifiConnectionInfo.decode(readValue(buffer)!);
      case 132:
        return AppRuntimeConfig.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// 原生平台 API
/// 由原生端实现，Flutter 端调用
class NativeApi {
  /// Constructor for [NativeApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  NativeApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// 获取应用运行时配置（主题模式、设备ID、访问令牌、连接设备名称、应用语言、日志开关）
  Future<AppRuntimeConfig> getAppRuntimeConfig() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.my_app_module.NativeApi.getAppRuntimeConfig$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as AppRuntimeConfig;
  }

  /// 关闭 Flutter Activity
  Future<void> closeFlutterActivity() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.my_app_module.NativeApi.closeFlutterActivity$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// 获取代理地址 (格式: ip:端口，例如 "192.168.1.100:8888")
  /// 返回空字符串表示不使用代理
  Future<String> getProxyAddress() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.my_app_module.NativeApi.getProxyAddress$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }

  /// 开始 WiFi 实时测速
  /// 通过 NativeFlutterApi.onWifiSpeedUpdated 回调返回结果
  Future<void> startWifiSpeedTest() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.my_app_module.NativeApi.startWifiSpeedTest$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// 停止 WiFi 测速
  Future<void> stopWifiSpeedTest() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.my_app_module.NativeApi.stopWifiSpeedTest$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// 判断当前连接的 WiFi 是否是当前设备（modem）的 WiFi
  /// 通过比较当前连接的 BSSID 与设备 WiFi 列表中的 BSSID
  /// 返回 true 表示当前连接到设备 WiFi，false 表示未连接或连接的是其他 WiFi
  Future<bool> isConnectedToDeviceWifi() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.my_app_module.NativeApi.isConnectedToDeviceWifi$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  /// 获取主 WiFi (Primary WiFi) 名称
  /// 优先返回 5G 主 WiFi 的 SSID，如果没有 5G 则返回第一个主 WiFi 的 SSID
  /// 返回 null 表示获取失败
  Future<String?> getPrimaryWifi() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.my_app_module.NativeApi.getPrimaryWifi$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as String?;
  }

  /// 打开手机 WiFi 设置页面
  Future<void> openWifiSettings() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.my_app_module.NativeApi.openWifiSettings$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// 获取当前连接 WiFi 的链路信息（频段、信道、信号强度）
  /// 返回 null 表示未连接 WiFi 或获取失败
  Future<WifiConnectionInfo?> getCurrentWifiConnectionInfo() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.my_app_module.NativeApi.getCurrentWifiConnectionInfo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as WifiConnectionInfo?;
  }
}

/// Flutter 回调 API
/// 由 Flutter 端实现，原生端调用
abstract class NativeFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// WiFi 速度更新回调
  void onWifiSpeedUpdated(WifiSpeedResult result);

  static void setUp(NativeFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.my_app_module.NativeFlutterApi.onWifiSpeedUpdated$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final WifiSpeedResult arg_result = args[0]! as WifiSpeedResult;
          try {
            api.onWifiSpeedUpdated(arg_result);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
