// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.hitrontech.myhitronpro.flutter

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object PigeonGeneratedPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** 主题模式枚举 */
enum class ThemeModeEnum(val raw: Int) {
  LIGHT(0),
  DARK(1),
  SYSTEM(2);

  companion object {
    fun ofRaw(raw: Int): ThemeModeEnum? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * WiFi 测速结果
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class WifiSpeedResult (
  /** WiFi 速度 (Mbps), -1 表示失败 */
  val speed: Double,
  /** 是否成功 */
  val isSuccess: Boolean,
  /** 错误信息 */
  val errorMessage: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WifiSpeedResult {
      val speed = pigeonVar_list[0] as Double
      val isSuccess = pigeonVar_list[1] as Boolean
      val errorMessage = pigeonVar_list[2] as String?
      return WifiSpeedResult(speed, isSuccess, errorMessage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      speed,
      isSuccess,
      errorMessage,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as WifiSpeedResult
    return PigeonGeneratedPigeonUtils.deepEquals(this.speed, other.speed) && PigeonGeneratedPigeonUtils.deepEquals(this.isSuccess, other.isSuccess) && PigeonGeneratedPigeonUtils.deepEquals(this.errorMessage, other.errorMessage)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.speed)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.isSuccess)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.errorMessage)
    return result
  }
}

/**
 * 当前连接 WiFi 的链路信息（频段 / 信道 / 信号强度）
 * 仅承载原生采集的原始值，展示格式（如 "5GHz (Ch 6, -42 dBm)"）由 Flutter 端拼接
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class WifiConnectionInfo (
  /** 频段 (2.4G, 5G, 6G)，来自 WifiUtils.checkCurrentWifiBand()，获取失败为 null */
  val band: String? = null,
  /** 信道，来自 WifiUtils.getChannelByFrequency(frequency)，获取失败为 null */
  val channel: Long? = null,
  /** 信号强度 (dBm)，来自 wifiInfo.getRssi()，获取失败为 null */
  val rssi: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WifiConnectionInfo {
      val band = pigeonVar_list[0] as String?
      val channel = pigeonVar_list[1] as Long?
      val rssi = pigeonVar_list[2] as Long?
      return WifiConnectionInfo(band, channel, rssi)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      band,
      channel,
      rssi,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as WifiConnectionInfo
    return PigeonGeneratedPigeonUtils.deepEquals(this.band, other.band) && PigeonGeneratedPigeonUtils.deepEquals(this.channel, other.channel) && PigeonGeneratedPigeonUtils.deepEquals(this.rssi, other.rssi)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.band)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.channel)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.rssi)
    return result
  }
}

/**
 * 应用运行时配置（启动时从原生一次性获取）
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AppRuntimeConfig (
  /** 主题模式 */
  val themeMode: ThemeModeEnum,
  /** 设备ID */
  val deviceId: String,
  /** 访问令牌 */
  val accessToken: String,
  /** 当前连接设备的名称，未连接时为 null */
  val connectedDeviceName: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AppRuntimeConfig {
      val themeMode = pigeonVar_list[0] as ThemeModeEnum
      val deviceId = pigeonVar_list[1] as String
      val accessToken = pigeonVar_list[2] as String
      val connectedDeviceName = pigeonVar_list[3] as String?
      return AppRuntimeConfig(themeMode, deviceId, accessToken, connectedDeviceName)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      themeMode,
      deviceId,
      accessToken,
      connectedDeviceName,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AppRuntimeConfig
    return PigeonGeneratedPigeonUtils.deepEquals(this.themeMode, other.themeMode) && PigeonGeneratedPigeonUtils.deepEquals(this.deviceId, other.deviceId) && PigeonGeneratedPigeonUtils.deepEquals(this.accessToken, other.accessToken) && PigeonGeneratedPigeonUtils.deepEquals(this.connectedDeviceName, other.connectedDeviceName)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.themeMode)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.deviceId)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.accessToken)
    result = 31 * result + PigeonGeneratedPigeonUtils.deepHash(this.connectedDeviceName)
    return result
  }
}
private open class PigeonGeneratedPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ThemeModeEnum.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WifiSpeedResult.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WifiConnectionInfo.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AppRuntimeConfig.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ThemeModeEnum -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is WifiSpeedResult -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is WifiConnectionInfo -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is AppRuntimeConfig -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/**
 * 原生平台 API
 * 由原生端实现，Flutter 端调用
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface NativeApi {
  /** 获取应用运行时配置（主题模式、设备ID、访问令牌、连接设备名称） */
  fun getAppRuntimeConfig(): AppRuntimeConfig
  /** 关闭 Flutter Activity */
  fun closeFlutterActivity()
  /**
   * 获取代理地址 (格式: ip:端口，例如 "192.168.1.100:8888")
   * 返回空字符串表示不使用代理
   */
  fun getProxyAddress(): String
  /**
   * 开始 WiFi 实时测速
   * 通过 NativeFlutterApi.onWifiSpeedUpdated 回调返回结果
   */
  fun startWifiSpeedTest()
  /** 停止 WiFi 测速 */
  fun stopWifiSpeedTest()
  /**
   * 判断当前连接的 WiFi 是否是当前设备（modem）的 WiFi
   * 通过比较当前连接的 BSSID 与设备 WiFi 列表中的 BSSID
   * 返回 true 表示当前连接到设备 WiFi，false 表示未连接或连接的是其他 WiFi
   */
  fun isConnectedToDeviceWifi(): Boolean
  /**
   * 获取主 WiFi (Primary WiFi) 名称
   * 优先返回 5G 主 WiFi 的 SSID，如果没有 5G 则返回第一个主 WiFi 的 SSID
   * 返回 null 表示获取失败
   */
  fun getPrimaryWifi(): String?
  /** 打开手机 WiFi 设置页面 */
  fun openWifiSettings()
  /**
   * 获取当前连接 WiFi 的链路信息（频段、信道、信号强度）
   * 返回 null 表示未连接 WiFi 或获取失败
   */
  fun getCurrentWifiConnectionInfo(): WifiConnectionInfo?

  companion object {
    /** The codec used by NativeApi. */
    val codec: MessageCodec<Any?> by lazy {
      PigeonGeneratedPigeonCodec()
    }
    /** Sets up an instance of `NativeApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: NativeApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.my_app_module.NativeApi.getAppRuntimeConfig$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getAppRuntimeConfig())
            } catch (exception: Throwable) {
              PigeonGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.my_app_module.NativeApi.closeFlutterActivity$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.closeFlutterActivity()
              listOf(null)
            } catch (exception: Throwable) {
              PigeonGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.my_app_module.NativeApi.getProxyAddress$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getProxyAddress())
            } catch (exception: Throwable) {
              PigeonGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.my_app_module.NativeApi.startWifiSpeedTest$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.startWifiSpeedTest()
              listOf(null)
            } catch (exception: Throwable) {
              PigeonGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.my_app_module.NativeApi.stopWifiSpeedTest$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopWifiSpeedTest()
              listOf(null)
            } catch (exception: Throwable) {
              PigeonGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.my_app_module.NativeApi.isConnectedToDeviceWifi$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isConnectedToDeviceWifi())
            } catch (exception: Throwable) {
              PigeonGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.my_app_module.NativeApi.getPrimaryWifi$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getPrimaryWifi())
            } catch (exception: Throwable) {
              PigeonGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.my_app_module.NativeApi.openWifiSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.openWifiSettings()
              listOf(null)
            } catch (exception: Throwable) {
              PigeonGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.my_app_module.NativeApi.getCurrentWifiConnectionInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getCurrentWifiConnectionInfo())
            } catch (exception: Throwable) {
              PigeonGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Flutter 回调 API
 * 由 Flutter 端实现，原生端调用
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class NativeFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by NativeFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      PigeonGeneratedPigeonCodec()
    }
  }
  /** WiFi 速度更新回调 */
  fun onWifiSpeedUpdated(resultArg: WifiSpeedResult, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.my_app_module.NativeFlutterApi.onWifiSpeedUpdated$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(resultArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(PigeonGeneratedPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
